# -*- coding: utf-8 -*-
"""Cópia de achados _perdidos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XdgMcmiw-E0iUzUIfom_NviZP9K3IkUo
"""

user_senha = {'massaki':'123'}
codigo = 0 # Inicializa com um valor que não sai do loop

while codigo != 3:
  print('\n--- MENU ---') # Adicionado para melhor legibilidade
  print('Digite uma das opções:')
  print('(1) Login')
  print('(2) Cadastro')
  print('(3) Sair')

  try:
    codigo = int(input('Escolha uma opção: '))
  except ValueError:
    print('Entrada inválida. Por favor, digite um número.')
    continue # Pula o resto do loop e mostra o menu novamente

  if codigo == 1:
    usuario_digitado = input('Digite seu nome de usuário: ')
    senha_digitada = input('Digite sua senha: ')

    if usuario_digitado in user_senha:
      if user_senha[usuario_digitado] == senha_digitada:
        print('Login bem-sucedido!')
        print(f'Bem-vindo, {usuario_digitado}!')
#=========================================================================
#Aqui vai a segunda tela com as outras funcionalidades


#=========================================================================
      else:
        print('Senha incorreta.')
    else:
      print('Usuário não encontrado.')

  elif codigo == 2:
    novo_usuario = input('Digite o nome de usuário para cadastro: ')
    if novo_usuario in user_senha:
      print('Este nome de usuário já existe. Por favor, escolha outro.')
    else:
      nova_senha = input('Digite a senha para o novo usuário: ')
      user_senha[novo_usuario] = nova_senha
      print(f'Usuário "{novo_usuario}" cadastrado com sucesso!')

  elif codigo == 3:
    print('Saindo do programa. Até mais!')

  else:
    print('Opção inválida. Por favor, escolha 1, 2 ou 3.')